---
  parserOptions:
    ecmaVersion: 2018
  env:
    es6: true
    browser: true
    jquery: true
  extends: eslint:recommended
  rules:
    dot-notation: [error, allowPattern: "^[A-Z]"]
    id-length: [error, exceptions: [i, j, e, x, y]]
    no-caller: error
    no-console: off
    no-empty: off
    no-implied-eval: error
    no-mixed-spaces-and-tabs: [error, smart-tabs]
    no-unused-vars:
     - error
     - vars: local
       args: none
    no-shadow: error
    no-unsafe-negation: error
    no-with: error
    valid-jsdoc:
      - error
      - requireReturn: false
        requireParamDescription: false
        requireReturnDescription: false

    indent: [error, tab, {SwitchCase: 1, MemberExpression: off, CallExpression: {arguments: off}}]
    semi: error
    brace-style: [error, 1tbs, allowSingleLine: true]
    linebreak-style: [error, unix]
    semi-spacing: error
    comma-spacing: error
    space-infix-ops: error
    template-curly-spacing: error
    space-before-function-paren: [error, {anonymous: never, named: never, asyncArrow: always}]
    space-before-blocks: error
    keyword-spacing:
      - error
      - before: true
        after: true
    no-useless-escape: off
    no-prototype-builtins: off
  globals:
    BigInt: readonly
    _: readonly
    XKit: writable
    XBridge: writable
    centerIt: writable
    Tumblr: writable
    add_tag: writable

    storage_max: writable
    storage_used: writable
    framework_version: writable
    getBridgeError: writable

    GM_flushStorage: writable
    GM_deleteAllValues: writable
    GM_getValue: writable
    GM_deleteValue: writable
    GM_setValue: writable
    GM_log: writable
    GM_openInTab: writable
    GM_listValues: writable
    GM_xmlhttpRequest: writable
