name: Rebuild Distribution

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Extensions/*'
      - 'Themes/*'

jobs:
  build:
    name: Autobuild extensions
    if: github.repository == 'new-xkit/XKit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Fetch and reset gh-pages
        run: |
          git remote set-branches --add origin gh-pages
          git fetch
          git checkout -f -t -b gh-pages origin/gh-pages
          git reset --hard master
      - name: Install dependencies
        run: npm ci
      - name: Install gulp-cli
        run: npm install gulp-cli
      - name: Build distribution
        run: gulp build
      - name: Commit changes
        run: |
          git add --force Extensions/
          git commit -m 'Rebuild Distribution'
      - name: Force-push to gh-pages
        run: git push -f
