name: Update gh-pages

on:
  push:
    branches:
      - 'master'
    paths:
      - 'Extensions/dist/*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Update gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Update gh-pages
        run: >
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

          npx gh-pages
          -u "github-actions-bot <support+actions@github.com>"
          --add
          --dist .
          --src "Extensions/dist/"
          --message 'Update Extensions/dist/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
